name: Collective Unconscious
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Collective Unconscious
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#0404a4'
    - '#050463'
    - '#171717'
    - '#1314c6'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
