name: Collective Unconscious
favicon: null
layout_spectrum: 0.49711
typography_spectrum: 1
title: Collective Unconscious
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b2326'
    - '#030303'
    - '#4a5255'
    - '#ab9895'
    - '#e1e1e1'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
