name: Collective Unconscious
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Collective Unconscious
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#0078cf'
    - '#35b2ec'
    - '#001ea2'
    - '#94cff1'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
